version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 1000
      runas: root
  AfterInstall:
    - location: scripts/unzip.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 1000
      runas: root
